
/**
 * This file is autogenerated. Do not edit manually.
 */    
package net.clesperanto.kernels;

import java.util.Objects;
import java.util.ArrayList;
import java.util.HashMap;

import net.clesperanto.core.ArrayJ;
import net.clesperanto.core.DeviceJ;
import net.clesperanto.core.Utils;

/**
 * Class containing all functions of tier 8 category
 */
public class Tier8 {

	/**
	 * Apply a morphological opening operation to a label image and afterwards   fills gaps between the labels using voronoi-labeling.
	 * Finally, the result   label image is masked so that all background pixels remain background pixels.
	 * Note: It is recommended to process isotropic label images.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input label image
	 * @param output ({@link ArrayJ}) - Output label image (default: None)
	 * @param radius (int) - Smoothing (default: 0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ smoothLabels(DeviceJ device, ArrayJ input, ArrayJ output, int radius) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.smooth_labels(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), radius));
    }
    
	/**
	 * Apply a morphological erosion and dilation of the label image with respect to     the connectivity of the labels.
	 * Note: It is recommended to process isotropic label images.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input label image
	 * @param output ({@link ArrayJ}) - Output label image (default: None)
	 * @param radius (int) - Smoothing (default: 0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ smoothConnectedLabels(DeviceJ device, ArrayJ input, ArrayJ output, int radius) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.smooth_connected_labels(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), radius));
    }
    
	/**
	 * Perform a 1D, 2D or 3D FFT (Fast Fourier Transform) on the input image.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image
	 * @param output ({@link ArrayJ}) - Output image (default: None)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ fft(DeviceJ device, ArrayJ input, ArrayJ output) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.fft(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw()));
    }
    
	/**
	 * Perform a 1D, 2D or 3D IFFT (Inverse Fast Fourier Transform) on the input image.
	 * The input image must be hermitian and the output image must be provided as the second argument.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image
	 * @param output ({@link ArrayJ}) - Output image
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ ifft(DeviceJ device, ArrayJ input, ArrayJ output) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(output, "output cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.ifft(device.getRaw(), input.getRaw(), output.getRaw()));
    }
    
	/**
	 * Perform a 1D, 2D or 3D convolution using FFT between an input image and a kernel Input image, psf kernel, and normalization image are expected to be in the spatial domain.
	 * The function will automatically pad the input image and psf kernel to the same size as the closest smooth size and will take care of the psf kernel centering.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image
	 * @param kernel ({@link ArrayJ}) - Kernel image
	 * @param output ({@link ArrayJ}) - Output image (default: None)
	 * @param correlate (boolean) - If true, convolution with the PSF reversed. (default: False)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ convolveFft(DeviceJ device, ArrayJ input, ArrayJ kernel, ArrayJ output, boolean correlate) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(kernel, "kernel cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.convolve_fft(device.getRaw(), input.getRaw(), kernel.getRaw(), output == null ? null : output.getRaw(), correlate));
    }
    
	/**
	 * Perform a 1D, 2D or 3D deconvolution using FFT between an input image and a psf kernel.
	 * The deconvolution is performed using the Richardson-Lucy algorithm and will requires a maximum iteration number.
	 * User can specify a normalization image (optional) and a regularization parameter (optional) to apply a Total Variation regularization.
	 * Input image, psf kernel, and normalization image are expected to be in the spatial domain.
	 * The function will automatically pad the input image and psf kernel to the same size as the closest smooth size and will take care of the psf kernel centering.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image
	 * @param psf ({@link ArrayJ}) - Kernel image
	 * @param normalization ({@link ArrayJ}) - Normalization image (default: None)
	 * @param output ({@link ArrayJ}) - Output image (default: None)
	 * @param iteration (int) - Maximum number of (default: 100)
	 * @param regularization (float) - Regularization parameter (default: 0.0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ deconvolveFft(DeviceJ device, ArrayJ input, ArrayJ psf, ArrayJ normalization, ArrayJ output, int iteration, float regularization) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(psf, "psf cannot be null");
		Objects.requireNonNull(normalization, "normalization cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.deconvolve_fft(device.getRaw(), input.getRaw(), psf.getRaw(), normalization == null ? null : normalization.getRaw(), output == null ? null : output.getRaw(), iteration, regularization));
    }
    
}
