/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cleObjectJNI {
  public final static native long new_Object__SWIG_0();
  public final static native long new_Object__SWIG_1(long jarg1, long jarg2, int jarg3);
  public final static native void delete_Object(long jarg1);
  public final static native void Object_Reset(long jarg1, Object jarg1_);
  public final static native long Object_Data(long jarg1, Object jarg1_);
  public final static native long Object_MemoryType(long jarg1, Object jarg1_);
  public final static native long Object_MemorySize(long jarg1, Object jarg1_);
  public final static native int Object_nDim(long jarg1, Object jarg1_);
  public final static native int Object_Size(long jarg1, Object jarg1_);
  public final static native long Object_Shape(long jarg1, Object jarg1_);
  public final static native long Object_Origin(long jarg1, Object jarg1_);
  public final static native long Object_Region(long jarg1, Object jarg1_);
  public final static native int Object_Type(long jarg1, Object jarg1_);
  public final static native String Object_GetDataType(long jarg1, Object jarg1_);
  public final static native boolean Object_IsDataType(long jarg1, Object jarg1_, String jarg2);
  public final static native String Object_GetObjectType(long jarg1, Object jarg1_);
  public final static native boolean Object_IsObjectType(long jarg1, Object jarg1_, String jarg2);
  public final static native boolean Object_IsMemoryType(long jarg1, Object jarg1_, long jarg2);
}
