/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class clesperanto {
  public static void setCle(SWIGTYPE_p_namespace value) {
    clesperantoJNI.cle_set(SWIGTYPE_p_namespace.getCPtr(value));
  }

  public static SWIGTYPE_p_namespace getCle() {
    return new SWIGTYPE_p_namespace(clesperantoJNI.cle_get(), true);
  }

}
