/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#ifndef __clesperanto_hpp
#define __clesperanto_hpp

#include "cleGPU.hpp"
#include "cleObject.hpp"

#include <type_traits>
#include <iostream>

namespace cle
{

class Clesperanto
{
private:
    std::shared_ptr<cle::GPU> m_gpu;

public:
    Clesperanto();
    ~Clesperanto() = default;

    template<class T =float>
    const cle::Object Create(const std::array<size_t,3>& ={1,1,1}, const std::string& ="buffer") const;
    template<class T =float>
    const cle::Object Push(const std::vector<T>& ={0}, const std::array<size_t,3>& ={1,1,1}, const std::string& ="buffer") const;
    template<class T =float>
    const std::vector<T> Pull(const cle::Object&) const;

    std::shared_ptr<GPU> Ressources();

    void AddImageAndScalar(Object&, Object&, float=0);
    void AddImagesWeighted(Object&, Object&, Object&, float=1, float=1);
    void AddImages(Object&, Object&, Object&);
    void SubtractImages(Object&, Object&, Object&);
    void DilateSphere(Object&, Object&);
    void ErodeSphere(Object&, Object&);
    void Equal(Object&, Object&, Object&);
    void EqualConstant(Object&, Object&, float=0);
    void GaussianBlur(Object&, Object&, float=1, float=1, float=0);
    void MeanBox(Object&, Object&, float=1, float=1, float=0);
    void MaximumBox(Object&, Object&, float=1, float=1, float=0);
    void MinimumBox(Object&, Object&, float=1, float=1, float=0);
    void Greater(Object&, Object&, Object&);
    void GreaterOrEqual(Object&, Object&, Object&);
    void GreaterConstant(Object&, Object&, float=0);
    void GreaterOrEqualConstant(Object&, Object&, float=0);
    void MaximumZProjection(Object&, Object&);
    void MaximumYProjection(Object&, Object&);
    void MaximumXProjection(Object&, Object&);
    void MaximumOfAllPixels(Object&, Object&);
    void MinimumZProjection(Object&, Object&);
    void MinimumYProjection(Object&, Object&);
    void MinimumXProjection(Object&, Object&);
    void MinimumOfAllPixels(Object&, Object&);
    void MeanSphere(Object&, Object&, int=1, int=1, int=0);
    void NonzeroMinimumBox(Object&, Object&, Object&);
    void NotEqual(Object&, Object&, Object&);
    void NotEqualConstant(Object&, Object&, float=0);
    void Absolute(Object&, Object&);
    void Sobel(Object&, Object&);
    void Set(Object&, float=0);
    void SetNonzeroPixelsToPixelindex(Object&, Object&);
    void DifferenceOfGaussian(Object&, Object&, float=0, float=0, float=0, float=1, float=1, float=0);
    void Smaller(Object&, Object&, Object&);
    void SmallerOrEqual(Object&, Object&, Object&);
    void SmallerConstant(Object&, Object&, float=0);
    void SmallerOrEqualConstant(Object&, Object&, float=0);
    void Copy(Object&, Object&);
    void DetectMaximaBox(Object&, Object&);
    void SumZProjection(Object&, Object&);
    void SumYProjection(Object&, Object&);
    void SumXProjection(Object&, Object&);
    void SumOfAllPixels(Object&, Object&);
    void ConnectedComponentLabellingBox(Object&, Object&);
    void ReplaceIntensity(Object&, Object&, float=0, float=0);
    void ReplaceIntensities(Object&, Object&, Object&);
    void SetColumn(Object&, int=0, float=0);
    void SumReductionX(Object&, Object&, int=0);
    void BlockEnumerate(Object&, Object&, Object&, int=0);  //! block enumarate fail when running with Image
    void FlagExistingLabels(Object&, Object&);
    void CloseIndexGapsInLabelMap(Object&, Object&, int=4096);
};

    template<class T>
    const cle::Object Clesperanto::Create(const std::array<size_t,3>& t_shape, const std::string& t_type) const
    {
        return this->m_gpu->Create<T>(t_shape, t_type);
    }

    template<class T>
    const cle::Object Clesperanto::Push(const std::vector<T>& t_array, const std::array<size_t,3>& t_shape, const std::string& t_type) const
    {
        return this->m_gpu->Push<T>(t_array, t_shape, t_type);
    }

    template<class T>
    const std::vector<T> Clesperanto::Pull(const cle::Object& t_object) const
    {
        return this->m_gpu->Pull<T>(t_object);
    }

} // namespace cle

#endif //__clesperanto_hpp


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_clesperantoJNI_cle_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  namespace arg1 ;
  namespace *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(namespace **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null namespace");
    return ;
  }
  arg1 = *argp1; 
  cle = arg1;
}


SWIGEXPORT jlong JNICALL Java_clesperantoJNI_cle_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  namespace result;
  
  (void)jenv;
  (void)jcls;
  result = cle;
  {
    namespace * resultptr = (namespace *) malloc(sizeof(namespace));
    memmove(resultptr, &result, sizeof(namespace));
    *(namespace **)&jresult = resultptr;
  }
  return jresult;
}


#ifdef __cplusplus
}
#endif

