name: ClesperantoJ tests

on: [push]

jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
