name: ClesperantoJ tests

on: [push]

jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    name: Test with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Execute the tests
        run: mvn clean test
